add dev branch and change hooks to reflect new branch

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -10,16 +10,17 @@ REPO_DIR=$(git rev-parse --show-toplevel)
 
 # copy this file to the git hooks directory
 cp "$REPO_DIR/.githooks/pre-commit" "$REPO_DIR/.git/hooks/"
+cd "$REPO_DIR/app"
 
 # run npm tests
 echo "Running npm test"
-cd "$REPO_DIR/app"
-export CI=true # enforce CI mode (treat warnings as errors)
-
-npm run build-ci
-if [ $? -ne 0 ]; then
-  echo "npm run build-ci failed"
-  exit 1
+if [[ "$BRANCH" =~ ^(master|main|develop)$ ]]; then
+	export CI=true # enforce CI mode (treat warnings as errors)
+	npm run build-ci
+	if [ $? -ne 0 ]; then
+	echo "npm run build-ci failed"
+	exit 1
+	fi
 fi
 
 npm run test-ci
